const countries = {
  'am-ET': 'Amharic',
  'ar-SA': 'Arabic',
  'fr-FR': 'French ',
  'en-GB': 'English ',
  'it-IT': 'Italian',
  'id-ID': 'Indonesian',
  'ja-JP': 'Japanese',
  'ko-KR': 'Korean',
  'pl-PL': 'Polish',
  'pt-BR': 'Portuguese ',
  'pt-PT': 'Portuguese ',
  'ro-RO': 'Romanian',
  'ru-RU': 'Russian',
  'es-ES': 'Spanish',
  'es-MX': 'Spanish ',
  'sw-KE': 'Swahili',
  'sv-SE': 'Swedish',
  'ta-IN': 'Tamil',
  'th-TH': 'Thai',
  'tr-TR': 'Turkish',
  'uk-UA': 'Ukrainian',
  'vi-VN': 'Vietnamese',
  'zh-CN': 'Chinese ',
  'zh-TW': 'Chinese ',
  'zu-ZA': 'Zulu',
  'hi-IN': 'Hindi',
  'bn-IN': 'Bengali',
  'pa-IN': 'Punjabi',
  'gu-IN': 'Gujarati',
  'kn-IN': 'Kannada',
  'de-DE': 'Germany'
}
